INSERT INTO `admins` (`name`, `email`, `password_hash`, `role`, `status`)
SELECT 'Admin', 'admin@gurukulclasses.com', '$2a$10$B/oz4Axmx/qSQ7pjKs.SJu5AsKBBppt33Y9hp/bDAfgHhs.yIUTLW', 'superadmin', 'active'
WHERE NOT EXISTS (SELECT 1 FROM `admins` LIMIT 1);

INSERT INTO `hero_sections` (`title`, `subtitle`, `description`, `button_text`, `button_link`, `background_image`, `badge`, `display_order`, `status`)
SELECT * FROM (
  SELECT 'IIT-JEE | Medical | Foundation Coaching' AS `title`, 'Since 2000' AS `subtitle`, 'Concept-first teaching, daily practice and real results - the Gurukul way.' AS `description`, 'Enquire Now' AS `button_text`, '#enquire' AS `button_link`, '/uploads/seed/hero-classroom.jpg' AS `background_image`, 'Admissions Open' AS `badge`, 1 AS `display_order`, 'active' AS `status`
  UNION ALL SELECT 'NEET, MH-CET & IIT-JEE Preparation in Kalyan and Bhiwandi', 'Top results year after year', 'Integrated programs that balance HSC scores with Entrance excellence.', 'Enquire Now', '#enquire', '/uploads/seed/hero-study.jpg', '5 Branches', 2, 'active'
  UNION ALL SELECT '10,000+ Successful Students & 6,000+ in Top Colleges', 'Proven track record', 'A legacy of trust built by thousands of doctors, engineers and scientists.', 'Enquire Now', '#enquire', '/uploads/seed/hero-students.jpg', '10k+ Alumni', 3, 'active'
  UNION ALL SELECT 'Admissions Open for VIII, IX, X, XI & XII Science', '2026 batches', 'Reserve your seat in our new academic session - limited capacity per batch.', 'Enquire Now', '#enquire', '/uploads/seed/about-teaching.jpg', 'Limited Seats', 4, 'active'
) AS seed_rows WHERE NOT EXISTS (SELECT 1 FROM `hero_sections` LIMIT 1);

INSERT INTO `results` (`student_name`, `exam_type`, `exam_label`, `result_value`, `year`, `student_photo`, `description`, `display_order`, `status`)
SELECT * FROM (
  SELECT 'Aarav S.' AS `student_name`, 'NEET' AS `exam_type`, 'NEET 2024' AS `exam_label`, '682 / 720' AS `result_value`, 2024 AS `year`, '/uploads/seed/bhagyashree-thakare.jpg' AS `student_photo`, 'Govt. Medical College' AS `description`, 1 AS `display_order`, 'active' AS `status`
  UNION ALL SELECT 'Ishika M.', 'IIT-JEE', 'JEE Advanced 2024', 'AIR 2,184', 2024, '/uploads/seed/vaibhav-thakare.jpg', 'IIT Bombay', 2, 'active'
  UNION ALL SELECT 'Riya P.', 'MH-CET', 'MH-CET 2024', '99.87 %ile', 2024, '/uploads/seed/hero-students.jpg', 'VJTI Mumbai', 3, 'active'
  UNION ALL SELECT 'Kabir T.', 'IIT-JEE', 'JEE Main 2024', '99.6 %ile', 2024, '/uploads/seed/about-teaching.jpg', 'NIT Surathkal', 4, 'active'
  UNION ALL SELECT 'Saanvi K.', 'NEET', 'NEET 2024', '656 / 720', 2024, '/uploads/seed/bhagyashree-thakare.jpg', 'Grant Medical College', 5, 'active'
  UNION ALL SELECT 'Vivaan R.', 'Board', 'HSC Science 2024', '94.50 %', 2024, '/uploads/seed/vaibhav-thakare.jpg', 'Mithibai College', 6, 'active'
  UNION ALL SELECT 'Anika D.', 'MH-CET', 'MH-CET 2024', '99.71 %ile', 2024, '/uploads/seed/hero-students.jpg', 'COEP Pune', 7, 'active'
  UNION ALL SELECT 'Rudra J.', 'IIT-JEE', 'JEE Advanced 2024', 'AIR 4,902', 2024, '/uploads/seed/about-teaching.jpg', 'IIT Madras', 8, 'active'
) AS seed_rows WHERE NOT EXISTS (SELECT 1 FROM `results` LIMIT 1);

INSERT INTO `gallery` (`title`, `image_path`, `category`, `description`, `display_order`, `status`)
SELECT * FROM (
  SELECT 'Science Lab Session' AS `title`, '/uploads/seed/hero-classroom.jpg' AS `image_path`, 'Academics' AS `category`, 'Hands-on practical learning in a modern classroom.' AS `description`, 1 AS `display_order`, 'active' AS `status`
  UNION ALL SELECT 'Felicitation Ceremony 2024', '/uploads/seed/hero-students.jpg', 'Events', 'Celebrating achievers and their families.', 2, 'active'
  UNION ALL SELECT 'Concept Lecture in Action', '/uploads/seed/about-teaching.jpg', 'Teaching', 'Interactive teaching with focused doubt solving.', 3, 'active'
  UNION ALL SELECT 'Self-Study Hours', '/uploads/seed/hero-study.jpg', 'Study', 'Discipline, revision and independent practice.', 4, 'active'
  UNION ALL SELECT 'Practical Class', '/uploads/seed/hero-classroom.jpg', 'Academics', 'Structured practice for every important concept.', 5, 'active'
  UNION ALL SELECT 'Topper Awards 2024', '/uploads/seed/hero-students.jpg', 'Events', 'Recognition for outstanding performance.', 6, 'active'
  UNION ALL SELECT 'Doubt-Solving Hours', '/uploads/seed/about-teaching.jpg', 'Teaching', 'One-on-one support when students need it most.', 7, 'active'
  UNION ALL SELECT 'Library Session', '/uploads/seed/hero-study.jpg', 'Study', 'Quiet time for reference work and revision.', 8, 'active'
  UNION ALL SELECT 'Foundation Batch', '/uploads/seed/hero-classroom.jpg', 'Foundation', 'Early preparation for younger students.', 9, 'active'
) AS seed_rows WHERE NOT EXISTS (SELECT 1 FROM `gallery` LIMIT 1);

INSERT INTO `press_releases` (`title`, `short_description`, `full_description`, `media_path`, `media_type`, `release_date`, `source_name`, `display_order`, `status`)
SELECT * FROM (
  SELECT 'Gurukul students sweep MH-CET 2024 top ranks' AS `title`, 'More than 80% of our XII Science batch crossed the 95-percentile mark in MH-CET 2024.' AS `short_description`, 'More than 80% of our XII Science batch crossed the 95-percentile mark in MH-CET 2024.' AS `full_description`, NULL AS `media_path`, NULL AS `media_type`, '2025-03-01' AS `release_date`, 'Gurukul Science Classes' AS `source_name`, 1 AS `display_order`, 'active' AS `status`
  UNION ALL SELECT 'New Anjurphata centre inaugurated in Bhiwandi', 'Our fifth branch opens its doors with state-of-the-art classrooms and a dedicated test centre.', 'Our fifth branch opens its doors with state-of-the-art classrooms and a dedicated test centre.', NULL, NULL, '2025-01-01', 'Gurukul Science Classes', 2, 'active'
  UNION ALL SELECT 'Felicitation of NEET & JEE 2024 toppers', 'A celebratory evening honouring 120+ students who secured admissions in top medical and engineering colleges.', 'A celebratory evening honouring 120+ students who secured admissions in top medical and engineering colleges.', NULL, NULL, '2024-08-01', 'Gurukul Science Classes', 3, 'active'
  UNION ALL SELECT 'Gurukul launches integrated Foundation programme', 'A redesigned VIII-X foundation track focused on concept building and early competitive exposure.', 'A redesigned VIII-X foundation track focused on concept building and early competitive exposure.', NULL, NULL, '2024-06-01', 'Gurukul Science Classes', 4, 'active'
) AS seed_rows WHERE NOT EXISTS (SELECT 1 FROM `press_releases` LIMIT 1);

INSERT INTO `blogs` (`title`, `slug`, `short_description`, `full_content`, `featured_image`, `author`, `category`, `publish_date`, `status`, `meta_title`, `meta_description`, `read_time`, `image_alt`, `body_json`, `highlights_json`, `display_order`)
SELECT * FROM (
  SELECT 'How to build a study routine that actually sticks' AS `title`, 'study-routine-that-sticks' AS `slug`, 'A practical routine for Class IX to XII students that keeps preparation steady without making every day feel overwhelming.' AS `short_description`, 'At Gurukul, we see the strongest results when students work with a simple rhythm: one concept block, one practice block and one short revision block. That structure keeps attention fresh and makes it easier to finish the day with a clear sense of progress.\n\nThe routine should also be realistic. A timetable that looks impressive on paper but fails after two days does more harm than good. We encourage students to choose fixed study hours, keep a short list of daily goals and review mistakes before sleep so the next day starts with clarity.' AS `full_content`, '/uploads/seed/hero-study.jpg' AS `featured_image`, 'Gurukul Team' AS `author`, 'Study Routine' AS `category`, '2026-06-01' AS `publish_date`, 'active' AS `status`, 'How to build a study routine that actually sticks' AS `meta_title`, 'A practical routine for Class IX to XII students that keeps preparation steady without making every day feel overwhelming.' AS `meta_description`, '4 min read' AS `read_time`, 'Student studying with books and notes' AS `image_alt`, '["At Gurukul, we see the strongest results when students work with a simple rhythm: one concept block, one practice block and one short revision block. That structure keeps attention fresh and makes it easier to finish the day with a clear sense of progress.","The routine should also be realistic. A timetable that looks impressive on paper but fails after two days does more harm than good. We encourage students to choose fixed study hours, keep a short list of daily goals and review mistakes before sleep so the next day starts with clarity."]' AS `body_json`, '["Keep one fixed study start time every day","Finish each session with quick mistake review","Reserve one block for practice questions","Protect sleep so learning actually locks in"]' AS `highlights_json`, 1 AS `display_order`
  UNION ALL SELECT 'Why weekly tests matter more than last-minute cramming', 'weekly-tests-matter', 'Weekly testing shows students where they stand, builds exam stamina and turns preparation into measurable improvement.', 'Our classrooms use chapter tests and cumulative tests because repetition under pressure improves recall. Students begin to understand how much time to spend on each question, when to move on and how to return to difficult problems without panic.\n\nThe other benefit is emotional. Once tests become a weekly habit, the exam feels familiar instead of frightening. Students also get regular feedback, which means correction happens early rather than after half the syllabus has drifted away.', '/uploads/seed/hero-classroom.jpg', 'Gurukul Team', 'Exam Strategy', '2026-06-01', 'active', 'Why weekly tests matter more than last-minute cramming', 'Weekly testing shows students where they stand, builds exam stamina and turns preparation into measurable improvement.', '5 min read', 'Science classroom with students and teacher', '["Our classrooms use chapter tests and cumulative tests because repetition under pressure improves recall. Students begin to understand how much time to spend on each question, when to move on and how to return to difficult problems without panic.","The other benefit is emotional. Once tests become a weekly habit, the exam feels familiar instead of frightening. Students also get regular feedback, which means correction happens early rather than after half the syllabus has drifted away."]', '["Expose weak chapters before they become major gaps","Train speed, accuracy and paper selection","Reduce anxiety by making tests feel routine","Turn every mistake into the next revision list"]', 2
  UNION ALL SELECT 'How parents can support preparation without adding pressure', 'parent-support-without-pressure', 'The best support at home is calm consistency: a clear routine, steady encouragement and the confidence to let mentors guide the process.', 'Instead of asking only about marks, we encourage families to ask about effort, revision and the next small target. Those questions reduce stress and keep the conversation focused on progress. A student who feels supported is more likely to ask for help early.\n\nParents can also protect the basics that matter most: sleep, meals, attendance and a quiet place to study. When the home environment is stable, the student can use the coaching plan more effectively and the mentor-team updates become easier to act on.', '/uploads/seed/about-teaching.jpg', 'Gurukul Team', 'Parent Guide', '2026-06-01', 'active', 'How parents can support preparation without adding pressure', 'The best support at home is calm consistency: a clear routine, steady encouragement and the confidence to let mentors guide the process.', '4 min read', 'Teacher guiding students in a classroom', '["Instead of asking only about marks, we encourage families to ask about effort, revision and the next small target. Those questions reduce stress and keep the conversation focused on progress. A student who feels supported is more likely to ask for help early.","Parents can also protect the basics that matter most: sleep, meals, attendance and a quiet place to study. When the home environment is stable, the student can use the coaching plan more effectively and the mentor-team updates become easier to act on."]', '["Ask about progress, not only scores","Keep the home routine calm and predictable","Stay connected with the academic team","Celebrate consistency as much as results"]', 3
) AS seed_rows WHERE NOT EXISTS (SELECT 1 FROM `blogs` LIMIT 1);
